console.log("***REPORT CARD***")
console.log("#Name       = Bethi Manideep")
console.log("#School     = PJHS")
console.log("#Grade      = 'A'")
console.log("#Section    = 'B'")
console.log("#Rollno     = 334")
console.log("1)MATH      = 80")
console.log("2)PHYSICS   = 90")
console.log("3)CHEMISTRY = 70")
console.log("< ==== TOTAL {240} MARKS ==== > ")
